spring:
  # ====== PostgreSQL ======
  config:
    jasypt:
      path: classpath:/jasypt.yml
      encryptor:
        bean: jasyptEncryptor

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true #console
        format_sql: true
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        highlight_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:postgresql://172.25.42.1:5441/corown?currentSchema=corown
    username: ENC(EZ0YI3gjy+xozEx/MciBsfOt9GzgnA6tw7Wm5FB9FnOgj/8hSpGG0aSjpWJVry/l)
    password: ENC(lD26XU0bDVXOJHiwYNQwT06GUWY5yHy1zw5YpeCNViDRRh65ZNvfgg4WSaYuKc/o)
    driver-class-name: org.postgresql.Driver
    pool-name: 'read-write-corown'
    sqlserver-dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    ddl-auto: 'validate'